
USE shopping_project;

-- Q1. What is the total revenue generated by male vs female customers?
SELECT gender,SUM(purchase_amount) AS Total_revenue
FROM customers
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id,purchase_amount
FROM CUSTOMERS 
WHERE discount_applied = 'Yes' AND purchase_amount >= (SELECT AVG(purchase_amount) AS AVG_purchase_amount FROM customers);

-- Q3. Which are the top 5 products with the height average review rating?
SELECT item_purchased,AVG(review_rating) as AVG_review_rating
FROM customers
GROUP BY item_purchased
ORDER BY AVG_review_rating DESC
LIMIT 5;

-- Q4. Compare the average purchase amounts between standards and express shipping?
SELECT shipping_type,ROUND(AVG(purchase_amount),2) AS AVG_purchase_amount
FROM customers
WHERE shipping_type IN ('standard','Express')
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non subscribers
SELECT subscription_status,
COUNT(customer_id) AS Total_customers,
AVG(purchase_amount) AS AVG_purchase_amount,
SUM(purchase_amount) AS SUM_purchase_amount
FROM customers
GROUP BY subscription_status
ORDER BY AVG_purchase_amount,SUM_purchase_amount;

-- Q6. Top customers by total spending
SELECT customer_id,
       COUNT(*) AS total_orders,
       SUM(purchase_amount) AS total_spent
FROM customers
GROUP BY customer_id
ORDER BY total_spent DESC
LIMIT 10;

-- Q7. Revenue by payment method
SELECT payment_method,
       COUNT(*) AS total_orders,
       SUM(purchase_amount) AS total_revenue
FROM customers
GROUP BY payment_method
ORDER BY total_revenue DESC;

-- Q8. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
100 * SUM(CASE WHEN discount_applied = 'Yes'
THEN 1
ELSE 0
END) / COUNT(*) AS Discount_rate
FROM customers
GROUP BY item_purchased
ORDER BY Discount_rate DESC LIMIT 5;

-- Q9. Segment customers into New, Returing, and Loyal based on their total number of previous purchases, and show the cost of each segment?
WITH customer_type AS(
SELECT customer_id,previous_purchases,
CASE
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases = 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customers
)
SELECT customer_segment, COUNT(*) AS Num_of_customers
FROM customer_type
GROUP BY customer_segment;

-- Q10. What are the top 3 most purchased products within each category?
WITH item_counts AS (
    SELECT 
        category,item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customers
    GROUP BY category, item_purchased
)
SELECT 
    category,item_purchased,total_orders,item_rank
    FROM item_counts
    WHERE item_rank <=3;

-- Q11. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
COUNT(customer_id) AS Total_buyers
FROM customers
WHERE previous_purchases > 5
GROUP BY subscription_status
ORDER BY Total_buyers;

-- Q12. What is the revenue contribution of each age group?
SELECT age_group,
SUM(purchase_amount) as  revenue_contribution
FROM customers
GROUP BY age_group
ORDER BY revenue_contribution DESC ;

-- Q13. Top customers by total spending
SELECT customer_id,
       COUNT(*) AS total_orders,
       SUM(purchase_amount) AS total_spent
FROM customers
GROUP BY customer_id
ORDER BY total_spent DESC
LIMIT 10;

